#!/bin/sh

rm -rf target/build && mkdir -p target/build

cross build --release --target x86_64-unknown-linux-musl
#cargo deb --no-build --target x86_64-unknown-linux-musl
strip target/x86_64-unknown-linux-musl/release/stratos
cp target/x86_64-unknown-linux-musl/release/stratos target/build/x86_64-linux-stratos
#cp target/x86_64-unknown-linux-musl/debian/stratos_*.*.*_amd64.deb target/build/

cross build --release --target x86_64-pc-windows-gnu
x86_64-w64-mingw32-strip target/x86_64-pc-windows-gnu/release/stratos.exe
cp target/x86_64-pc-windows-gnu/release/stratos.exe target/build/x86_64-windows-stratos.exe
